-- 15/08/2013 03:42:23 PM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE T_Conciliation (AD_Client_ID DECIMAL(10) NOT NULL, AD_Org_ID DECIMAL(10) NOT NULL, AD_PInstance_ID DECIMAL(10) DEFAULT NULL , AmountNotReconciled DECIMAL(10) DEFAULT NULL , C_BankAccount_ID DECIMAL(10) DEFAULT NULL , C_BankStatement_ID DECIMAL(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy DECIMAL(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, T_Conciliation_ID DECIMAL(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy DECIMAL(10) NOT NULL, CONSTRAINT T_Conciliation_Key PRIMARY KEY (T_Conciliation_ID)) ENGINE=InnoDB
;

-- 15/08/2013 03:42:41 PM VET
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
CREATE TABLE T_Conciliationline (AD_Client_ID DECIMAL(10) NOT NULL, AD_Org_ID DECIMAL(10) NOT NULL, AD_PInstance_ID DECIMAL(10) DEFAULT NULL , C_BankStatementLine_ID DECIMAL(10) DEFAULT NULL , C_Charge_ID DECIMAL(10) DEFAULT NULL , ChargeAmt DECIMAL(22, 10) DEFAULT NULL , C_Payment_ID DECIMAL(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy DECIMAL(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsManual CHAR(1) DEFAULT NULL CHECK (IsManual IN ('Y','N')), IsReconciled CHAR(1) DEFAULT NULL CHECK (IsReconciled IN ('Y','N')), StatementDate DATE DEFAULT NULL , StmtAmt DECIMAL(22, 10) DEFAULT NULL , T_Conciliationline_ID DECIMAL(10) NOT NULL, TenderType CHAR(1) DEFAULT NULL CHECK (TenderType IN ('Y','N')), TrxAmt DECIMAL(22, 10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy DECIMAL(10) NOT NULL, CONSTRAINT T_Conciliationline_Key PRIMARY KEY (T_Conciliationline_ID)) ENGINE=InnoDB
;

